server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezon=UTC
    username: root
    password: root
  # 缓存配置
  cache:
    type: ehcache
  main:
    allow-circular-references: true
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


jetcache:
  statIntervalMinutes: 1  # 每隔一分钟统计一次数据
  remote:
    default:
      type: redis
      keyConvertor: fastjson  # 指定类转换为String的工具
      valueEncode: java
      valueDecode: java
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50
    sms:
      type: redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson  # 指定类转换为String的工具

      poolConfig:
        maxTotal: 50



# 开启mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: assign_id
      table-prefix: tb_
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 1

# Spring log
#logging:
#  # 设置分组
#  group:
#    ebank: com.yruns.config, com.yruns.controller
#    service: com.yruns.service
  # 分组设置日志级别
#  level:
#    root: info
#    ebank: warn
#    service: debug






testrandomcase:
  book:
    id: ${random.int}
    name: ${random.value}
    uuid: ${random.uuid}
    publishTime: ${random.long}

